"""
Pantheon sandbox API models — the single source of truth for inter-service communication.

All teams import from this module. Do not duplicate these models elsewhere.
Coordinate with Pablo before making any changes.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field

# --- Type aliases -----------------------------------------------------------

type AnalysisType = Literal["static", "dynamic", "both"]
type RiskLevel = Literal["low", "medium", "high", "critical"]
type JobStatus = Literal["queued", "running", "complete", "failed"]


# --- IOC sub-models ---------------------------------------------------------

class NetworkIOCs(BaseModel):
    """Network-layer indicators of compromise."""

    ips: list[str] = Field(default_factory=list, description="Malicious IP addresses")
    domains: list[str] = Field(default_factory=list, description="Malicious domains")
    ports: list[int] = Field(default_factory=list, description="Destination ports")
    protocols: list[str] = Field(default_factory=list, description="Network protocols used")
    urls: list[str] = Field(default_factory=list, description="Full URLs contacted")


class FileIOCs(BaseModel):
    """File-system indicators of compromise."""

    sha256: str = Field(default="", description="SHA-256 hash of the sample")
    md5: str = Field(default="", description="MD5 hash of the sample")
    paths: list[str] = Field(
        default_factory=list,
        description="File paths created or modified by the malware",
    )


# --- Request / Response models ----------------------------------------------

class AnalyzeRequest(BaseModel):
    """Request body for POST /sandbox/analyze."""

    job_id: str = Field(description="Unique job identifier, generated by the caller")
    file_content_b64: str = Field(description="Base64-encoded bytes of the malware sample")
    filename: str = Field(description="Original filename of the sample")
    analysis_type: AnalysisType = Field(
        default="both",
        description="Which analysis pipeline(s) to run",
    )


class AnalyzeResponse(BaseModel):
    """Response body for POST /sandbox/analyze."""

    job_id: str
    status: JobStatus


class ThreatReport(BaseModel):
    """Full analysis report returned by GET /sandbox/report/{job_id}."""

    job_id: str
    status: JobStatus
    malware_type: str = Field(description="e.g. 'WSH dropper', 'ransomware loader'")
    obfuscation_technique: str = Field(
        description="e.g. 'javascript-obfuscator _0x string array'"
    )
    behavior: list[str] = Field(
        default_factory=list,
        description="Observed or inferred behavioral indicators",
    )
    network_iocs: NetworkIOCs = Field(default_factory=NetworkIOCs)
    file_iocs: FileIOCs = Field(default_factory=FileIOCs)
    registry_iocs: list[str] = Field(
        default_factory=list,
        description="Registry keys created, modified, or queried",
    )
    risk_level: RiskLevel
    affected_systems: list[str] = Field(
        default_factory=list,
        description="Systems or data stores potentially impacted",
    )
    gemini_summary: str = Field(
        description="Plain-language behavioral analysis from Gemini"
    )
    remediation_hints: list[str] = Field(
        default_factory=list,
        description="High-level remediation suggestions from static/dynamic analysis",
    )


class IOCReport(BaseModel):
    """Flat IOC list returned by GET /sandbox/iocs/{job_id}."""

    ips: list[str] = Field(default_factory=list)
    domains: list[str] = Field(default_factory=list)
    file_hashes: dict[str, str] = Field(
        default_factory=dict,
        description="Hash type -> hex digest, e.g. {'sha256': '...', 'md5': '...'}",
    )
    file_paths: list[str] = Field(default_factory=list)
    ports: list[int] = Field(default_factory=list)
    registry_keys: list[str] = Field(default_factory=list)
    cve_ids: list[str] = Field(default_factory=list)
    urls: list[str] = Field(default_factory=list)


class HealthResponse(BaseModel):
    """Response body for GET /sandbox/health."""

    status: Literal["ok", "degraded"]
    docker_available: bool
    version: str = "0.1.0"


# --- KnowledgeStore models ---------------------------------------------------


class MemoryEntry(BaseModel):
    """A single agent output stored in the KnowledgeStore."""

    job_id: str
    agent_name: str
    run_number: int
    temperature: float
    output: str = Field(description="Agent's full markdown/text output for this run")
    created_at: str = ""


class StoreMemoryRequest(BaseModel):
    """Request body for POST /sandbox/memory."""

    job_id: str
    agent_name: str
    temperature: float = Field(default=0.3, description="Gemini temperature used for this run")
    output: str = Field(description="Agent's full output to persist")


class StoreMemoryResponse(BaseModel):
    """Response body for POST /sandbox/memory."""

    run_number: int = Field(description="1-based index of this run for the (job_id, agent_name) pair")  # noqa: E501
    total_runs: int = Field(description="Total runs stored for this (job_id, agent_name) pair")


class SimilarJob(BaseModel):
    """A job with behavioral similarity to the queried job."""

    job_id: str
    malware_type: str
    similarity: float = Field(description="Jaccard similarity score 0.0-1.0")
    shared_behaviors: list[str] = Field(
        default_factory=list,
        description="Behavior strings present in both jobs",
    )


# --- Event system models ----------------------------------------------------


class EventType(str, Enum):
    """All event types emitted by agents and tools to the EventBus."""

    AGENT_ACTIVATED = "agent_activated"
    AGENT_COMPLETED = "agent_completed"
    HANDOFF = "handoff"
    TOOL_CALLED = "tool_called"
    TOOL_RESULT = "tool_result"
    IOC_DISCOVERED = "ioc_discovered"
    STAGE_UNLOCKED = "stage_unlocked"
    PROCESS_EVENT = "process_event"
    NETWORK_EVENT = "network_event"
    ANALYSIS_COMPLETE = "analysis_complete"
    ERROR = "error"


class AgentName(str, Enum):
    """Canonical agent identifiers used in events."""

    ZEUS = "zeus"
    ATHENA = "athena"
    HADES = "hades"
    APOLLO = "apollo"
    ARES = "ares"
    HERMES = "hermes"


class PantheonEvent(BaseModel):
    """A single structured event broadcast through the EventBus."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    ts: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    type: EventType
    agent: AgentName | None = None
    tool: str | None = None
    job_id: str | None = None
    payload: dict[str, Any] = Field(default_factory=dict)  # Any: payload schema varies per EventType


class ProcessEvent(BaseModel):
    """A file, registry, or process event captured by Procmon on the Windows VPS."""

    event_type: Literal["file_write", "registry_write", "process_spawn"]
    path: str
    value: str | None = None
    process: str
    pid: int


class NetworkEvent(BaseModel):
    """A network event captured by FakeNet-NG or tshark on the Windows VPS."""

    event_type: Literal["dns_query", "http_request", "tcp_connect"]
    host: str
    path: str | None = None
    payload_preview: str | None = None


class AttackStage(BaseModel):
    """A confirmed stage of the malware's attack chain."""

    stage_id: str
    label: str
    description: str
    icon: str


class DetonationResult(BaseModel):
    """Combined output from a live Windows VPS detonation run."""

    process_events: list[ProcessEvent] = Field(default_factory=list)
    network_events: list[NetworkEvent] = Field(default_factory=list)
    error: str | None = None
