"""
Pantheon Swarm Manager — sophisticated orchestration loop for malware analysis pipeline.

This module manages the entire analysis swarm:
- Routes samples from Artemis (file watcher) through the Zeus orchestrator
- Tracks job IDs through each agent (Athena → Hades → Apollo → Ares)
- Emits workflow events to the EventBus for real-time dashboard visualization
- Maintains a persistent queue of pending and in-progress analyses
- Handles retry logic for failed analyses
- Synthesizes results across multiple runs of the same sample
"""

from __future__ import annotations

import asyncio
import logging
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from pathlib import Path

logger = logging.getLogger("pantheon.swarm")


class AnalysisStatus(str, Enum):
    """Possible states of a malware analysis job in the swarm."""

    PENDING = "pending"  # Waiting to be routed to Zeus
    ROUTING = "routing"  # Being classified by Athena
    ANALYZING = "analyzing"  # Being analyzed by Hades
    ENRICHING = "enriching"  # IOCs being enriched by Apollo
    PLANNING = "planning"  # Response plans being generated by Ares
    COMPLETE = "complete"  # Full analysis complete
    FAILED = "failed"  # Analysis failed at some stage
    RETRY = "retry"  # Waiting for retry after failure


@dataclass
class SwarmJob:
    """Represents a single malware sample flowing through the swarm pipeline."""

    job_id: str  # Unique identifier for this analysis run
    sample_path: str  # Path to the malware sample file
    sample_name: str  # Filename of the sample
    status: AnalysisStatus = AnalysisStatus.PENDING
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    error_message: str | None = None
    retry_count: int = 0
    max_retries: int = 3

    # Agent outputs
    threat_classification: str | None = None  # Athena's severity/category
    threat_report: dict | None = None  # Hades' analysis report
    enriched_iocs: str | None = None  # Apollo's enhanced IOCs
    response_plan: str | None = None  # Ares' containment/remediation/prevention


class SwarmManager:
    """
    Central orchestration manager for the Pantheon malware analysis swarm.

    Coordinates:
    - Sample intake from Artemis file watcher
    - Routing through Zeus → Athena → Hades → Apollo → Ares pipeline
    - Job persistence and state tracking
    - EventBus emission for dashboard visualization
    - Retry logic for failed analyses
    - Behavioral synthesis across multiple runs
    """

    def __init__(self) -> None:
        self._pending: asyncio.Queue[SwarmJob] = asyncio.Queue()
        self._in_progress: dict[str, SwarmJob] = {}
        self._completed: dict[str, SwarmJob] = {}
        self._failed: dict[str, SwarmJob] = {}
        self._lock = asyncio.Lock()

    async def ingest_sample(self, sample_path: Path) -> str:
        """
        Accept a new malware sample and queue it for analysis.

        Returns the job_id for this analysis run.
        """
        job_id = str(uuid.uuid4())[:8]
        job = SwarmJob(
            job_id=job_id,
            sample_path=str(sample_path),
            sample_name=sample_path.name,
        )
        logger.info("Swarm: ingested sample %s → job %s", sample_path.name, job_id)
        await self._pending.put(job)
        return job_id

    async def route_next(self) -> SwarmJob | None:
        """
        Pop the next pending job from the queue and move it to in_progress.

        Returns the job, or None if queue is empty.
        """
        if self._pending.empty():
            return None

        job = await self._pending.get()
        async with self._lock:
            self._in_progress[job.job_id] = job
        job.status = AnalysisStatus.ROUTING
        job.updated_at = datetime.now(UTC)
        logger.info("Swarm: routing job %s to Athena (triage)", job.job_id)
        return job

    async def update_job_status(
        self,
        job_id: str,
        status: AnalysisStatus,
        output: dict | str | None = None,
    ) -> None:
        """
        Update the status of an in-progress job and store its output.

        Called by each agent (Athena, Hades, Apollo, Ares) as handoff happens.
        """
        async with self._lock:
            job = self._in_progress.get(job_id)
            if not job:
                logger.warning("Swarm: job %s not found in in_progress", job_id)
                return

            job.status = status
            job.updated_at = datetime.now(UTC)

            # Store agent-specific outputs
            if status == AnalysisStatus.ROUTING and isinstance(output, str):
                job.threat_classification = output
            elif status == AnalysisStatus.ANALYZING and isinstance(output, dict):
                job.threat_report = output
            elif status == AnalysisStatus.ENRICHING and isinstance(output, str):
                job.enriched_iocs = output
            elif status == AnalysisStatus.PLANNING and isinstance(output, str):
                job.response_plan = output

        logger.info("Swarm: job %s status updated to %s", job_id, status.value)

    async def complete_job(self, job_id: str) -> SwarmJob | None:
        """
        Mark a job as complete and move it from in_progress to completed.
        """
        async with self._lock:
            job = self._in_progress.pop(job_id, None)
            if not job:
                logger.warning("Swarm: job %s not found for completion", job_id)
                return None
            job.status = AnalysisStatus.COMPLETE
            job.updated_at = datetime.now(UTC)
            self._completed[job_id] = job

        logger.info("Swarm: job %s completed successfully", job_id)
        return job

    async def fail_job(self, job_id: str, error: str) -> SwarmJob | None:
        """
        Mark a job as failed. If retries remain, move to RETRY state.
        Otherwise move to FAILED.
        """
        async with self._lock:
            job = self._in_progress.pop(job_id, None)
            if not job:
                logger.warning("Swarm: job %s not found for failure", job_id)
                return None

            job.error_message = error
            job.retry_count += 1

            if job.retry_count < job.max_retries:
                job.status = AnalysisStatus.RETRY
                await self._pending.put(job)
                logger.warning(
                    "Swarm: job %s failed (%s), queueing retry %d/%d",
                    job_id,
                    error,
                    job.retry_count,
                    job.max_retries,
                )
            else:
                job.status = AnalysisStatus.FAILED
                self._failed[job_id] = job
                logger.error(
                    "Swarm: job %s failed after %d retries: %s",
                    job_id,
                    job.max_retries,
                    error,
                )

            job.updated_at = datetime.now(UTC)

        return job

    def get_job(self, job_id: str) -> SwarmJob | None:
        """Retrieve a job by ID from any state (pending, in_progress, completed, failed)."""
        return (
            self._in_progress.get(job_id)
            or self._completed.get(job_id)
            or self._failed.get(job_id)
        )

    async def get_pending_count(self) -> int:
        """Return the number of pending samples waiting to be analyzed."""
        return self._pending.qsize()

    async def get_in_progress_count(self) -> int:
        """Return the number of samples currently being analyzed."""
        async with self._lock:
            return len(self._in_progress)

    async def get_completed_count(self) -> int:
        """Return the number of successfully completed analyses."""
        async with self._lock:
            return len(self._completed)

    async def get_failed_count(self) -> int:
        """Return the number of failed analyses."""
        async with self._lock:
            return len(self._failed)

    async def stats(self) -> dict[str, int]:
        """Return current statistics of the swarm."""
        return {
            "pending": await self.get_pending_count(),
            "in_progress": await self.get_in_progress_count(),
            "completed": await self.get_completed_count(),
            "failed": await self.get_failed_count(),
        }


# Global singleton instance
_swarm: SwarmManager | None = None


async def get_swarm() -> SwarmManager:
    """Get or create the global SwarmManager instance."""
    global _swarm
    if _swarm is None:
        _swarm = SwarmManager()
    return _swarm
